version: '3'
services:
  server:
    build: ./server
    expose: 
      - "3020"
    volumes:
      - ./server/src:/srv/app/server/src
    ports:
      - "3020:3020"
    command: npm start
  
  client:
    build: ./client
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/srv/app/client/src
      - ./client/public:/srv/app/client/public
    links:
      - server
    command: npm start
    

